### ISSUE TITLE
Internally reusing the file sending capability

### ISSUE THREAD

**Issue by mindplay-dk** [nuintun/koa-files#203]
I'm writing a custom middleware that needs to send files. (I'm porting it from Express to Koa, actually.)

I'd like to reuse the capability from your middleware to send a specific file.

Here's a simplified example:

```ts
import { Middleware } from "koa";
import server from "koa-files";
import path from "node:path";
import fs from "node:fs";

export function myMiddleware(): Middleware {
  return (context, next) => {
    const rootPath = "/home/user/app/files";
    const fileName = "folder/file.jpg";
  
    console.log("exists", fs.existsSync(path.join(rootPath, fileName))); // true
  
    context.path = fileName; // I've also tried `context.url = filename` and `context.path = "/"+filename`
  
    server(rootPath)(context, next);
  };
}
```

I see "exists: true" on the console, so I know the file exists.

But the response on the page is always just "Not found".

I know it's probably unusual to create and call middleware from within another middleware - but the library doesn't export a function to just send a specific file on demand, and since my `rootPath` can't be determined at startup, I have to create and run the middleware every time. That would probably be fine, since your middleware doesn't do any heavy initialization.

But it just doesn't work. Any idea why?

**Comment by mindplay-dk** [comment]
I debugged it, and it is going all the way through your middleware without errors - but for some reason, Koa does not emit the response. I'm guessing `server(rootPath)(context, next)` is the wrong way to delegate to another middleware, but I can't find anything in the Koa manual or anywhere else about delegating to a different middleware...

**Comment by nuintun** [comment]
try

```js
import { Middleware } from https://github.com/koajs/koa;
import server from https://github.com/nuintun/koa-files;
import path from ["node:path"](https://nodejs.org/api/path.html);
import fs from ["node:fs"](https://nodejs.org/api/fs.html);

export function myMiddleware(): Middleware {
  return async (context, next) => {
    const rootPath = "/home/user/app/files";
    const fileName = "folder/file.jpg";
  
    console.log("exists", fs.existsSync(path.join(rootPath, fileName))); // true
  
    context.path = fileName; // I've also tried `context.url = filename` and `context.path = "/"+filename`
  
    await server(rootPath)(context, next);
  };
}
```

**Comment by mindplay-dk** [comment]
Yes, adding the missing `await` works - thanks!
